package com.vaja.game.GUI;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JFrame;

import com.vaja.game.MainGame;

public class InterfaceGui extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form HomeGUI
     */
    public InterfaceGui() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mB4 = new com.vaja.game.GUI.MB();
        mB3 = new com.vaja.game.GUI.MB();
        mB2 = new com.vaja.game.GUI.MB();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);

        
        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new BorderLayout());
        
       
        
        mB4.setText("New Game");
        mB4.setToolTipText("");
        mB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mB4ActionPerformed(evt);
            }
        });
//        mB4.setSize(100, 30);
        mB4.setBounds(60, 270, 230, 50);
        jPanel1.add(mB4);
        
        
        mB2.setText("Exit Game");
        mB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mB2ActionPerformed(evt);
            }
        });
        mB2.setBounds(480, 270, 230, 50);
//        mB2.setSize(100, 30);
        jPanel1.add(mB2);
        

        
        
        //img charector
        jLabel3.setIcon(new javax.swing.ImageIcon("res/Gui/Std_logo.png"));
        jLabel3.setMaximumSize(new java.awt.Dimension(200,150));
        jLabel3.setBounds(280, 230, 80, 120);
        jLabel3.setSize(200, 150);
        jPanel1.add(jLabel3);

        //LOGO
        jLabel4.setIcon(new javax.swing.ImageIcon("res/Gui/logo4.png"));// NOI18N
        jLabel4.setBounds(230, 50, 340, 120);
        jLabel4.setSize(500, 120);
        jPanel1.add(jLabel4);

        
        jLabel2.setIcon(new javax.swing.ImageIcon("res/Gui/bg4.jpg")); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(750, 450));
        jLabel2.setMinimumSize(new java.awt.Dimension(750, 450));
        jLabel2.setPreferredSize(new java.awt.Dimension(750, 450));
        jLabel2.setBounds(0, 0, 750, 400);
        jPanel1.add(jLabel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        		);
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        

        pack();
    }// </editor-fold>          DesktopLauncher              

    
    private void mB4ActionPerformed(java.awt.event.ActionEvent evt) {    
    	MainGame obj = new MainGame();
    	obj.RunGame();
         this.dispose();    	
        }             

    private void mB2ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        System.exit(0);
    }                                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.vaja.game.GUI.MB mB2;
    private com.vaja.game.GUI.MB mB3;
    private com.vaja.game.GUI.MB mB4;
    // End of variables declaration                   
	@Override
	public void actionPerformed(ActionEvent arg0) {
		// TODO Auto-generated method stub
		
	}
}

